const actionTypes = {
  // CHART_INITIALIZE: 'CHART_INITIALIZE',
  CHART_SUCCESS: 'CHART_SUCCESS',
  CHART_ERROR: 'CHART_ERROR',
  // EXCHANGE_INITIALIZE: 'EXCHANGE_INITIALIZE',
  EXCHANGE_SUCCESS: 'EXCHANGE_SUCCESS',
  EXCHANGE_ERROR: 'EXCHANGE_ERROR',
  // PORTFOLIO_INITIALIZE: 'PORTFOLIO_INITIALIZE',
  PORTFOLIO_SUCCESS: 'PORTFOLIO_SUCCESS',
  PORTFOLIO_ERROR: 'PORTFOLIO_ERROR',
}
export default actionTypes